spring.application.name=University Project

spring.data.mongodb.uri=mongodb+srv://amitkumaramitkumar15351_db_user:4EHgb8LZGsC7cdfj@cluster0.j70rd9i.mongodb.net/todo_db?retryWrites=true&w=majority&tls=true

app.jwt.secret=university_todo_super_secret_key_min_32_characters_here!
app.jwt.expiration=86400000

server.port=8080

app.cors.allowed-origins=http://localhost:5173,http://localhost:3000