name: Deploy Spring Boot App v1.1

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            mkdir -p ~/app
            cd ~/app

            if [ -d "University-Project" ]; then
              cd University-Project
              git pull origin main
            else
              git clone https://github.com/Iamit-kumarI/University-Project.git
              cd University-Project
            fi

            mvn clean package -DskipTests

            pkill -f university-todo || true
            sleep 2

            nohup java -jar target/university-todo-0.0.1-SNAPSHOT.jar > app.log 2>&1 &

            echo "Deployment completed successfully"
            exit 0